version: "3.8"

services:
  fastapi-service:
    build: .
    container_name: fastapi-baseline
    ports:
      - "8081:8080" # TODO Change the host port
    restart: unless-stopped
    environment:
      - TZ=UTC
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    volumes:
      - ./logs:/app/logs
    # Если нужно GPU
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
